### ISSUE TITLE
Maven "clean install" fails when docker-dev is running because of Postgres port conflict

### ISSUE THREAD

**Issue by NickGrantONS** [ONSdigital/rm-sample-service#59]
Running "mvn clean install" runs some integration tests, which fail because they try to start a Postgres instance on port 6432, which is being used by the Postgress instance on local dev machines which are using docker-compose / rm-docker-dev.

The port should be changed to something in the > 30,000 range so it doesn't clash when people are doing local dev work.

**Comment by gemmai95** [comment]
See collection exercise for example: https://github.com/ONSdigital/rm-collection-exercise-service

**Comment by NickGrantONS** [comment]
Fixed in PR https://github.com/ONSdigital/rm-sample-service/pull/60
